### ISSUE TITLE
v9 Testing/Feedback

### ISSUE THREAD

**Issue by maxence-charriere** [maxence-charriere/go-app#519] opened 2021-04-21 11:47 UTC
Hello there, 

I know it is pretty close to the v8 release but I had been working on a **new version that removes the need to call [Compo.Update()](https://go-app.dev/reference#Compo.Update) to update what is displayed on the screen**.

Unfortunately, it brings some API changes and since some of you are using this package, I wanted to share that work with you and get some feedback before releasing the new version.

## Install
```
go get -u -v github.com/maxence-charriere/go-app/v9@3653b5c
```

Then replace your imports in your code

## What changed

- No need to call Update anymore!
- `Compo.Defer()` has been removed. Now all Dispatch()/Defer() are done from `Context.Dispatch(func(Context))`
- `Context.Dispatch(func())` is now `Context.Dispatch(func(Context))`, and UI elements are always checked before launching Component lifecycle event or HTML event handlers
- Context has now a `Defer(func(Context))` method that launches the given function after a component has been updated. It can be handy to perform action after the display is complete, like scrolling to a given location
- Context has now an `After()` function that launches a function on the UI goroutine after the given time without blocking the UI
- There is a new Component lifecycle event: `OnUpdate(Context)`: it is launched only when a component gets updated by a parent, and should replace a scenario where a `Compo.Defer()` call was called in a `Render() app.UI` method
- `Context` is now an interface. Fields are now methods:
  - `Src` => `Src()`
  - `JSSrc` => `JSSrc()`
  - `AppUpdateAvailable` => `AppUpdateAvailable()`
  - `Page` => `Page()`
- `Context` has now a `Context.Emit(func())` method that launches the given function and notifies parents to update their state. This should be used when implementing your own event handlers in your components, in order to properly update parent components that set a function to the event handler
- `Context` has now method to encrypt and decrypt data
  - `Encrypt(v interface{}) ([]byte, error)`
  - `Decrypt(crypted []byte, v interface{}) error`
- `Context` has now a method that returns device id: `DeviceID() string`
- [EXPERIMENTAL] Changed the API for `Stack()`

## API design decisions

- This release focuses mainly on getting the usage of the package more reactive
- The API is designed to make unrecommended things difficult. A good example would be calling a `Context.Dispatch()` inside a `Render()` method
- With the exception of `Handler` and JS-related things, everything that you might need is now available from `Context`. Still thinking about whether I should move `Compo.ResizeContent()` and `Compo.ValueTo` in `Context` though

Please let me know what you think and where it makes things difficult to solve your problem. I will try to help you solve those and/or iterate to make things better.

@pojntfx @beanpole135 @ZackaryWelch @mar1n3r0

Thanks

**Comment by beanpole135** [comment] 2021-04-21 13:00
Great! I will try it out this weekend and let you know how it goes!

**Comment by simulot** [comment] 2021-04-21 13:20
>     * The API is designed to make unrecommended things difficult. A good example would be calling a `Context.Dispatch()` inside a `Render()` method

This is welcome. I'm trying to collect information from several sources asynchronously, and update the screen as long as info is coming. I was struggling with unwanted server side rendering that was crashing, and with the results screen not updated.  
I have removed Defer and Dispatch, and it works better now... Now, I can focus on my my quirks. 
Great job!

**Comment by pojntfx** [comment] 2021-04-21 14:38
Awesome! I'll try porting [pojntfx/bofied](https://github.com/pojntfx/bofied) to it and see how it goes. I really like the removal of `.Update`, which will probably make it everything much more readable and those with a React background like myself really comfortable :)

**Comment by ZackaryWelch** [comment] 2021-04-21 14:39
Excited to look at this soon!

**Comment by pojntfx** [comment] 2021-04-21 16:11
The port went really smoothly, see https://github.com/pojntfx/bofied/pull/1 - much smaller diff than v7 → v8, with most changes being removing dependencies on components that used v8 internally.

Some notes:

- `OnUpdate` is awesome and mitigates https://github.com/maxence-charriere/go-app/issues/447, although I still wrap the "controlled" component with https://github.com/pojntfx/bofied/pull/1/files#diff-82abcbfa96ef8fd491dd59bc21bacf0632a73fdac971f62c9a95c39e4ea274c6 to make it a bit simpler to use (see https://github.com/pojntfx/bofied/pull/1/files#diff-d067161e1e050833a07c85c6ed409e1546cca235f68a4be0c12f905b37d122adR85-R94 for an example)
- I had some troubles migrating from `Update` to `Emit` at first - in liwasc and bofied, I've pulled up most of the state into `providers` for a structure like this:

  ```plaintext
  SetupProvider(IdentityProvider(SetupShell(DataProvider(DataShell))))
  ```

  Now if I wish to update the state from a component in `DataShell`, say by calling `SetText("Hello, world!")` from the latter which sets the state in `DataProvider`, it does not automatically re-render; wrapping the call to `SetText` in `Context.Emit` fixes it, and the component properly re-renders. If one pulls state down to `DataShell` and uses `c.text = "Hello, world!"`, it works w/o emit, as expected. Took some time to figure that out, but still much better than calling `.Update` :)

**Comment by ZackaryWelch** [comment] 2021-04-22 01:06
It's worked out well for me, and I've been able to use most of the changes in one way or another. Without too much difficulty, mostly just needed to pass context around more.

**Comment by maxence-charriere** [comment] 2021-04-22 01:53
It is really hard in Go to set up observable properties while keeping a simple and light API. 

The trick I used is that with `Context` and `Dispatcher`, now I know all the entry points where a component update might be required. I got a little inspiration from game engines that take input for a short moment of time before updating their state. It is what go-app is doing now. Each let's say 15 ms, the engine keeps a single reference on the components that might need to update their state and perform it at once.

@pojntfx, the only edge case was when you are creating an event handler. Eg. `CompoB` allows setting an event handler. `CompoA` embeds `CompoB`. When the trigger happens,  `CompoB` is calling the handler, the engine knows there is something to do with `CompoB` but not `CompoA` since when calling the handler, the only context available is the B one. `Emit()` allows `CompoB` parents to be notified that they might need to update their state too.

**Comment by maxence-charriere** [comment] 2021-04-22 02:03
```
With the exception of Handler and JS-related things, everything that you might 
need is now available from Context.Still thinking about whether I should move 
Compo.ResizeContent() and Compo.ValueTo in Context though
```

What do you think about this?

**Comment by maxence-charriere** [comment] 2021-04-22 14:20
@pojntfx Could you give it a try without calling `Emit()`, I just pushed an update that calls it by default when it is an EventHandler.

```
go get -u -v github.com/maxence-charriere/go-app/v9@0e7d7c5
```

**Comment by ZackaryWelch** [comment] 2021-04-22 14:30
> ```
> With the exception of Handler and JS-related things, everything that you might 
> need is now available from Context. Still thinking about whether I should move 
> Compo.ResizeContent() and Compo.ValueTo() in Context though
> ```
> 
> What do you think about this?

I think that's a good idea.

Giving your latest update a try

**Comment by ZackaryWelch** [comment] 2021-04-22 15:32
Works great! Very smooth

**Comment by pojntfx** [comment] 2021-04-22 15:38
Awesome, after updating dropping `Emit` from all event handlers the view is stil in sync with the state, even if the state is outside of the component (https://github.com/pojntfx/bofied/commit/bfd57c209335748fb5ba7ca10d77adea276efa50) :muscle:

**Comment by pojntfx** [comment] 2021-04-23 19:54
Not sure if this has happened in v9 or is present before, but is the `role` attribute missing? I was expecting to be able to use `.Role`, but it doesn't exist (see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role for the attribute). Would be required for accessibility reasons :)

**Comment by maxence-charriere** [comment] 2021-04-23 20:07
I ll add it, thanks for reporting it :)

**Comment by pojntfx** [comment] 2021-04-23 22:52
Oh and I found one more edge case in which I have to manually call `.Update`, although I'm not sure if it's fixable: I'm attaching an event handler to the document (to close a modal with the escape key): https://github.com/pojntfx/bofied/blob/main/pkg/components/modal.go#L79-L85 which I'm handling in another component: https://github.com/pojntfx/bofied/blob/main/pkg/components/file_explorer.go#L595-L599 - in this case, neither `.Emit` nor `.Dispatch` seem to work and a manual `.Update` is necessary.

**Comment by maxence-charriere** [comment] 2021-04-24 01:12
@pojntfx did you try Emit there? I ll take a look if i can auto handle this.

**Comment by beanpole135** [comment] 2021-04-24 11:42
ok, I just finished testing it out and it is working great!
You can see the changes here: https://github.com/beanpole135/go-site-templates/pull/1/files

Notes:
* All the SESSION.Update() calls were removed without impact... so I think you can say that works perfectly!
* I converted a bunch of my pages/dialogs into app.Comp elements - no issues getting them to refresh like before when some top-level change happened, so that is working great too!
* Add add a quick background timer function to simulate some external "change" getting pushed into the global data structure, and this is the only place where I still need to use the `SESSION.Update()` function to trigger a page refresh. I am not sure if there is any way around that though - since it is an external process-initiated change, rather than something that happens due to app-functionality.

**Comment by beanpole135** [comment] 2021-04-24 12:20
Follow-up with Note 3 above:
* It appears that if the app.Compo structure contains a *pointer* to some other value, then the component does not automatically update if the value getting pointed at changes. (I compared two values: a "string" and a "*string" value within the same struct).

If you can support checking pointer values within app.Compo, that would probably make the external cache system work fine without ever needing to call the Update() function again.

**Comment by beanpole135** [comment] 2021-04-24 12:28
Nevermind - even updating a string field within the structure from an external timer function does not seem to trigger the element update either. I had a flaw in my test.
So it looks like the component still needs some kind of trigger to tell the app to refresh if the component struct is changed by an external source.

**Comment by simulot** [comment] 2021-04-24 16:48
I'm trying to build a page with elements received one at  a time from a websocket connection. 
The idea is to build dynamically a tree of objects as results arrive. At the end of incoming flow, the tree looks like:
- SearchPage
  - SearchResults
     - Result
     - Result
     - ...
  
First attempt was to make all of them as a Compo, linked with pointers and slices. I was unable to get them updated as I want. Either fully rendered when the websocket closes, or just one result displayed, and many panics when calling result.Update directly or wrapped in Emit. 

So I have kept just SearchPage as Compo, and the rest is normal data structure. 
The SearchPage Render function renders all parts as needed.  The down side of this is the render function is getting complicated, difficult to read.

Maybe I don't have understood how it should work.

**Comment by maxence-charriere** [comment] 2021-04-24 17:30
@pojntfx Just pushed a modification that may solve your problem:
```
go get -u -v github.com/maxence-charriere/go-app/v9@841eccd
```

Taking a look at @beanpole135 and @simulot problems now.

**Comment by maxence-charriere** [comment] 2021-04-24 17:35
@beanpole135 Look like you are not calling `RandomizeOnTimer()` from a component lifecycle event or an event handler. In that scenario it is normal that you have to trigger manualy the update.

**Comment by maxence-charriere** [comment] 2021-04-24 17:48
@simulot I have the feeling this is not related to be a v9 problem but more how would you build your search screen.
If I'm correct I invite you to open another issue with this specific problem, where you can give me more context in order to help you.

**Comment by beanpole135** [comment] 2021-04-26 12:17
From my perspective I think v9 works perfectly fine as long as you are not planning to remove the Update() call completely. I see no problem with using Update() after externally-initiated changes to data structures, and kind of expected it.

Good work!

**Comment by maxence-charriere** [comment] 2021-04-26 12:25
Yep, I don’t want to remove it since there will 100% chances that there is scenario I did not think of :).

**Comment by pojntfx** [comment] 2021-04-26 14:49
@maxence-charriere Thanks, your update fixed events from window not being handled! Another 24 SLOC down (https://github.com/pojntfx/bofied/commit/2336b1c50c4a8668e93e129832220b62a7b72982) :+1::

https://user-images.githubusercontent.com/28832235/116102702-372b3c00-a6af-11eb-9361-9d54d6e01454.mp4

I agree with @beanpole135's take here - while automatic updates are awesome, the existence of `Compo.Update` is always a good fallback :)

**Comment by maxence-charriere** [comment] 2021-04-29 15:02
Hey there, i just made a modification to Context to make it an interface. The problem was that the current implementation did not allow duck typing with contexts derived from app.Context. There is also some add, here is the changelog:
- `Context` is now an interface. Fields are now methods:
  - `Src` => `Src()`
  - `JSSrc` => `JSSrc()`
  - `AppUpdateAvailable` => `AppUpdateAvailable()`
  - `Page` => `Page()`
- `Context` has now method to encrypt and decrypt data
  - `Encrypt(v interface{}) ([]byte, error)`
  - `Decrypt(crypted []byte, v interface{}) error`
- `Context` has now a method that returns device id: `DeviceID() string`

I'm also considering adding a [Mediator](https://en.wikipedia.org/wiki/Mediator_pattern) implementation in order to make communication between components easier. Let me know what you think.

**Comment by pojntfx** [comment] 2021-04-29 22:13
Sounds good to me! Integrated the new changes in https://github.com/pojntfx/bofied/commit/145ea22180b9ba9b9993e005324d9d6ccca94625.

I have noticed a regression/bug though; the service worker seems to cache `""` which fails with `Uncaught (in promise) DOMException: Cache.addAll() encountered a network error` (see https://pojntfx.github.io/bofied/):

![image](https://user-images.githubusercontent.com/28832235/116624584-7aeca280-a948-11eb-978f-73a107aede08.png)

The frontend `cmd` in question can be found here: https://github.com/pojntfx/bofied/blob/main/cmd/bofied-frontend/main.go

**Comment by maxence-charriere** [comment] 2021-04-30 07:42
@pojntfx fixed on 
```
go get -u -v github.com/maxence-charriere/go-app/v9@d0daf02
```

**Comment by ZackaryWelch** [comment] 2021-04-30 22:56
Context changes work well for me. I like the idea of an interface for communicating between components. Not sure if that's the best way but it depends on your implementation.

**Comment by maxence-charriere** [comment] 2021-05-19 13:21
Hey folks, I had made some changes to the way HTML attributes are set. No breaking change here but if you could test it and tell me if there are regressions, would be very helpful.

Thank you!

```
go get -u -v github.com/maxence-charriere/go-app/v9@dfb5822
```

**Comment by pojntfx** [comment] 2021-05-19 13:55
Thanks for the update! Transition was smooth; here are the changes I had to do: https://github.com/pojntfx/bofied/pull/9

I created a `Controlled` helper component which sets the DOM properties in addition to the HTML attributes here: https://github.com/pojntfx/bofied/blob/main/pkg/components/controlled.go (usage here: https://github.com/pojntfx/bofied/blob/update-go-app/pkg/components/text_editor.go#L107-L133) - it seems to be required to make it possible to set DOM properties (i.e. the `hidden` property in the PR linked above). Before this update, some of the HTML attributes (`hidden` and `readonly` in my case) seemed to be set as well when the HTML attributes are set, while others (i.e. `value`) weren't - is this intentional or a regression?

**Comment by maxence-charriere** [comment] 2021-05-19 14:07
@pojntfx properties like boolean and `value` were not correctly set before because setting the attribute was setting only the initial value.

The change now sets the DOM field directly.
You may not require the wrapper anymore.

**Comment by pojntfx** [comment] 2021-05-19 15:14
Hmm; for all of the values, the HTML attributes are changed, but the DOM properties aren't being set; it works when I use my wrapper component. Happens for `readOnly` and `hidden`, but is not necessary for `value`, where the DOM property is being set. In this concrete example, I'm toggling `hidden`, and it only toggles the HTML attribute/default value, not the DOM property:

![image](https://user-images.githubusercontent.com/28832235/118837241-e9c47800-b8c4-11eb-9bb7-079226e8fd04.png)

**Comment by maxence-charriere** [comment] 2021-05-21 07:39
@pojntfx looks like I did not write case-sensitive boolean correctly. Just fixed it. Could you try it with:
```
go get -u -v github.com/maxence-charriere/go-app/v9@9b096a0
```

**Comment by beanpole135** [comment] 2021-05-25 11:16
Just a quick note that using `v9@692ebc6` fixed a rather persistent bug in one of my sites where the "value" of an HTML input on one page kept bleeding over into another HTML input after a page change.
Good work!

**Comment by pojntfx** [comment] 2021-05-27 09:19
@maxence-charriere Sorry for not getting back to you earlier, but you're right, `v9@692ebc6` fixes it! All uses of my wrapper are now gone (https://github.com/pojntfx/bofied/pull/9/commits/62e3bb5ca9b28698c2e2b5b131f167369960ffc7) :rocket:

**Comment by nathanhack** [comment] 2021-07-17 19:42
Any thoughts on when this might be merged?

**Comment by maxence-charriere** [comment] 2021-07-17 20:58
I think its for soon. I have it running in https://murlok.io and it is working pretty good. Have to update the docs too.  Will start that work on Monday.

**Comment by nathanhack** [comment] 2021-07-29 19:33
@maxence-charriere I made a toy example (https://github.com/nathanhack/go-app-test) using github.com/maxence-charriere/go-app/v9 v9.0.0-20210522022017-692ebc622535 and code from https://github.com/maxence-charriere/go-app-demo.

But I get a 404 from the server when I switched the handler from v6 to v9.

I'm new to project so it could be complete ignorance on my part.

**Closed** 2021-09-22 08:34 UTC
Labels: help wanted, working on it
