### ISSUE TITLE
The new release seems to ignore "BackgroundColor" in app.Handler.

### ISSUE THREAD

**Issue by oderwat** [maxence-charriere/go-app#838] opened 2023-06-27 16:33 UTC
When compiling with the 3.7.1 release, we have the wrong background color while the app loads in the browser. It seems as if it is not applied anymore. We now get the dark default one with white text. This is very much the opposite of what we usually need for our applications, and holds us back using the new release in production and beta.

Edit: I fixed it by adding a raw-header (using important!), but I think it should work without.

**Comment by maxence-charriere** [comment] 2023-06-27 18:59
Thanks for reporting it. I made a branch that might fix the problem: https://github.com/maxence-charriere/go-app/pull/839
Can you try and let me know how it goes?

**Comment by maxence-charriere** [comment] 2023-06-27 19:20
This should be fixed in v9.7.2. Feel free to reopen if the problem is still here. Again sorry for the disturbance.

**Closed by maxence-charriere** 2023-06-27 19:20 UTC

**Comment by oderwat** [comment] 2023-06-27 21:46
Sorry. I was not there to test. The 9.7.2 is working as expected. Thank you.
