### ISSUE TITLE
Migrating to modules

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#312] opened 2020-01-30 10:00 UTC
Is migrating to modules on the roadmap for next release ? 

I had issues with it when it comes to forking the repo where internal/http import paths had to be renamed.

**Comment by maxence-charriere** [comment] 2020-01-30 10:04
I did not get issues using it with go mod.

I might be mistaken but path problem when forking a repo is a problem related to how Go is working.

**Comment by mar1n3r0** [comment] 2020-01-30 10:52
The simplest way to demonstrate it is:

1. fork repository

2. go get -u -v github.com/forked-repo/app/cmd/goapp

This gets interrupted with the following output:

`forked-repo/app/cmd/goapp/build.go:11:2: use of internal package github.com/maxence-charriere/app/internal/http not allowed`

**Comment by orsinium** [comment] 2020-01-30 12:29
I faced another issue. Steps to reproduce:

```bash
cd ~/go/src/github.com/orsinium
take demo
go mod init
goapp init -v                                          
goapp run -v -b chrome
```

Output:

```
‣ building wasm app
    go: finding github.com/maxence-charriere/app latest
    go: finding golang.org/x/net latest
    github.com/orsinium/demo/cmd/demo-wasm
‣ building server
    github.com/orsinium/demo/cmd/demo-server
‣ installing go wasm support file
‣ generating etag
‣ generating service worker
‣ generating icons
x open src/github.com/maxence-charriere/app/logo.png: no such file or directory
```

**Comment by orsinium** [comment] 2020-01-30 12:35
Yes, `export GOPATH="/home/gram/go"` helped.

**Comment by maxence-charriere** [comment] 2020-01-30 13:34
I probably gonna get rid of `goapp` anyway, I m working on another version that will not require it anymore.

**Comment by maxence-charriere** [comment] 2020-02-24 22:10
Hi there, just giving some news about this issue.

I had been working for a while on the next version of this package and I'm currently finishing up things for a near to come release.

While there will be breaking changes, this will not be an issue anymore since all the internal packages will no longer exist.

You can take a peek [here](https://github.com/maxence-charriere/app/tree/6.0.0).

**Comment by maxence-charriere** [comment] 2020-03-08 03:32
Hello,
I just pushed the necessary to make the package compatible with go mod.
It took me a while to fully understand how it works but it is here now.

The package can be used by `go get github.com/maxence-charriere/go-app/v6`.

Closing this, let me know if version related stuff is missing.

**Closed by maxence-charriere** 2020-03-08 03:32 UTC

**Comment by mar1n3r0** [comment] 2020-03-08 08:34
Thanks for the update. Due to the breaking changes and the direction of v6 I am intending to lock my fork to v5 and continue developing and maintaining it for the sake of projects in use which rely on the flexibility provided with it.

**Comment by maxence-charriere** [comment] 2020-03-08 15:44
Thanks for the feedback. Could you develop the flexibility point?

I would like to have a feedback on why the new version does not suits your needs.

Would be also curious about what stuff you are building with it.

You may not be the only one that feels that way and actually i might be able to pull something to make html templating back if it is a deal breaker.

**Comment by mar1n3r0** [comment] 2020-03-08 16:07
For me the winning point of v5 is the ease of reusing various ready-made open source templates like forms, css, templates directly with no added layer of complexity. The transparency of the interpreter also makes it easy to debug when things break. The addition of the internal objects on top is pretty no doubt about it but it adds a lot of complexity and rewriting when you just want to reuse html directly with little tweaking made directly in the string. 

Currently I am using it for single page applications and I was amazed how ease it was to get back anchor scrolling which was disabled in settings but available with a one-line change. 

All Go frontend frameworks I have seen based on wasm are overly complex and quickly locking it all in internal caveats for the sake of standing out from the crowd. What attracted me to this project in the first place is that it is very minimal overlay on top while very capable and at the same time very transparent and easy to extend.
